tbselenium/tbdriver.py, tbselenium/test/test_tbdriver.py
As of today, the [Firefox Webdriver](https://github.com/SeleniumHQ/selenium/blob/194d041e97904fe023f5c03967c7a5dc70310d89/py/selenium/webdriver/firefox/webdriver.py#L67) of Selenium tries to find the
location of the [Firefox binary](https://github.com/SeleniumHQ/selenium/blob/194d041e97904fe023f5c03967c7a5dc70310d89/py/selenium/webdriver/firefox/firefox_binary.py#L157) [in the PATH environment variable of
Linux](https://github.com/SeleniumHQ/selenium/blob/194d041e97904fe023f5c03967c7a5dc70310d89/py/selenium/webdriver/firefox/firefox_binary.py#L202).
Modifying the PATH environment variable, we ensure we use the firefox
binary from the Tor Browser Bundle, avoiding possible problems in the
future once we introduce Marionette tests.
=> Make sure we run the Firefox binary from TBB

.travis.yml, tbselenium/test/test_tbdriver.py
We use lsof to get libraries loaded by TB and make sure that
libxul.so and libstdc++.so.6 are loaded from TBB dirs.
Fixes #16.
=> Add a test to make sure we load the Firefox libraries from TBB dirs.

tbselenium/tbdriver.py, tbselenium/test/test_tbdriver.py
This argument is only used if we launch a new process.
Add tests to make sure when we specify a temporary datadir,
TBB's data dir stay unchanged.
Fixes issue #5
=> Add an argument to specify the tor data directory.

run_tests.py, tbselenium/common.py, tbselenium/tbdriver.py, tbselenium/test/test_tbdriver.py, tbselenium/utils.py
Better handle non-default SOCKS ports.
Raise an exception if the caller wants us to launch a Tor process
on a custom (!=9150) port.
Refactor utils module. Use SHA-256 instead of MD5.
Run Stem test on a different SOCKS port (9250).
=> Better handle custom ports (issue #8)

setup.py, tbselenium/tbdriver.py, tbselenium/test/conftest.py
We don't depend on pyvirtualdisplay, except when running tests locally.
We should mention this "developer dependency" in the README.md to
make sure that people install pyvirtualdisplay if they want to run tests
with XVFB..
=> Remove pyvirtualdisplay from setup py

tbselenium/tbdriver.py, tbselenium/test/__init__.py, tbselenium/test/test_tbdriver.py
We ran into issue with relative during CI tests, where TBB_PATH is supplied
as a relative path. Now we convert the paths as early as possible
during the initialization of TorBrowserDriver and in __init__.py
where we read TBB_PATH from the environment variable.
Fixes #27
=> Convert all the TBB related paths to absolute paths during init

setup.py, tbselenium/common.py, tbselenium/tbdriver.py, tbselenium/test/test_env.py, tbselenium/test/test_examples.py, tbselenium/test/test_tbdriver.py, tbselenium/test/test_utils.py, tbselenium/utils.py
Dependency for tld package was only needed to get TLD+1 for URLs exempt
from canvas defense. Yet, we don't need the canvas_exceptions for
TBB >= 4.5a3 and we can expect the caller to pass allowed hosts
instead of URLs if they need to use TorBrowserDriver with outdated TB
versions.
We rename the argument canvas_exceptions to canvas_allowed_hosts to
signal the change.
=> Remote tld dependency, rename canvas_exceptions to canvas_allowed_hosts

tbselenium/test/test_env.py, tbselenium/test/test_tbdriver.py, tbselenium/utils.py
Remove dependency to deprecated commands module.
Use subprocess.getstatusoutput as it is implemented in Python 3.
Remove is_port_listening function which depends on run_cmd.
Now we use is_connectable from selenium.
Fixes #24
=> Issue24 remove deprecated command module

tbselenium/test/test_env.py, tbselenium/test/test_tbdriver.py, tbselenium/utils.py
Remove unused assert_installed routine.
Remove unused test_tor_daemon_running test.
Run test_default_tor_ports only on CI, where Tor is guaranteeed
to be running.
Remove lsof and shell dependency (per #24) of the loaded library test
(test_should_load_tbb_firefox_libs). Use process memory map.
Check hostname before adding to db for canvas exemption.
=> Avoid running shell commands.

.travis.yml, requirements-dev.txt, tbselenium/tbdriver.py, tbselenium/test/test_env.py, tbselenium/test/test_tbdriver.py, tbselenium/test/test_utils.py, tbselenium/utils.py
Add Python3 support based on 2to3 recommendations.
Remove redundant get_hash_of_directory function.
Add a function to get the last modification time of a directory.
Add requirements-dev.txt, the Python packages needed for testing.
Fix int-string comparison error.
Remove `six` package, replace `iteritems` with `items`.
Remove barely useful is_png test.
Handle WebDriverException during TBDriverTest initialization.
=> Add Python 3 support

.travis.yml, tbselenium/tbdriver.py, tbselenium/test/test_tbdriver.py, tbselenium/utils.py
Run CI tests with two versions of TBB.
Check TBB version before running bundled font test.
Fix version string regexp, add Chinese localized TBB to CI tests.
Set preference to avoid language spoofing alert box in Chinese TBB.
Change the way we check the network error page.
Add 5.5.4 Chinese TBB to CI tests.
=> Ci multiple tbb versions

.travis.yml, tbselenium/tbdriver.py, tbselenium/test/conftest.py, tbselenium/test/fixtures.py, tbselenium/test/test_addons.py, tbselenium/test/test_browser.py, tbselenium/test/test_bundled_fonts.py, tbselenium/test/test_env.py, tbselenium/test/test_examples.py, tbselenium/test/test_exceptions.py, tbselenium/test/test_screenshot.py, tbselenium/test/test_security_slider.py, tbselenium/test/test_stem.py, tbselenium/test/test_tbdriver.py
Refactor test code, divide test_tbdriver into smaller modules
Better clean up if Tor connection fails.
Fix exception handling error for the Stem test.
Change default test behavior to use running system Tor.
This speeds up the test and make them more resilient
against (TBB) Tor bootstrap failures.
Add a test for Hidden Service access.
Run py.test with -v (verbose)
=> Refactor tests, default to system tor for the tests

.travis.yml, tbselenium/common.py, tbselenium/exceptions.py, tbselenium/tbdriver.py, tbselenium/test/conftest.py, tbselenium/test/fixtures.py, tbselenium/test/test_addons.py, tbselenium/test/test_browser.py, tbselenium/test/test_bundled_fonts.py, tbselenium/test/test_exceptions.py, tbselenium/test/test_screenshot.py, tbselenium/test/test_security_slider.py, tbselenium/test/test_stem.py, tbselenium/test/test_tbdriver.py, tbselenium/utils.py
Start running test on container-based infrastructure.
Use Stem to start a Tor process on CI.
Remove external timeout for the fixtures.
Disable WebGL tests on CI.
Use curly braces for environment variables in Travis config.
Add one second sleep after TorBrowserDriver initialization.
This prevents cases where the driver doesn't respond to
commands.
=> Cache TBB downloads on Travis, remove external timeout

.travis.yml, tbselenium/.coveragerc
Don't download TBB tarball if it's already in Travis cache.
Exclude test files from coverage tests.
=> Don't download TBB tarball if it's already in the cache

examples/stem_adv.py, tbselenium/tbdriver.py, tbselenium/test/test_exceptions.py
Get only the modified time of the top director (not recursively).
=> Add optional control_port argument to TorBrowserDriver's init

travis.sh
When the CI tests are rerun due to an error, port 9150 remains in use, e.g.
https://travis-ci.org/webfp/tor-browser-selenium/jobs/152723582#L519
This should be due to remaining Tor processes from the previous test run.
This commit kills all Tor process before starting a new CI test run.
=> Kill tor processes before running a test.

tbselenium/tbdriver.py, tbselenium/test/fixtures.py
Revise quit() to prevent obvious errors during deinitialization.
=> Print TB logs when a test fails.

tbselenium/test/fixtures.py
This is to fix issue #74 . It initializes `last_err` to `None`. In case `last_err` is not redefined in the for loop, the `last_err` will be evaluated in the condition `to_raise` as `False`.
=> initialize last_err

setup.py
Test module was not included in the distributed package,
e.g. the one available on PyPI.
Update the package version to 0.2.
Fixes #75.
=> Include test module in tbselenium package

tbselenium/test/test_bundled_fonts.py
New fontconfig version (shipped in Ubuntu 16.04) added a space in
the log line we test.
=> Check for possible space in the fontconfig log.

examples/bridge.py, tbselenium/tbdriver.py, tbselenium/test/test_bridge.py
Add a new argument called `default_bridge_type` to choose between several bridge types already shipped with TBB.
To use bridges that are not shipped with the Tor Browser Bundle, one still needs to set prefs.
=> Add an option to use a different default bridge

.travis.yml
This is to avoid `easy_install` errors such as this: https://travis-ci.org/webfp/tor-browser-selenium/jobs/311084038#L571
Remove the `ignore-installed` flag, which was added to address the same issue.
=> Use pip instead of easy_install for installing tbselenium.

tbselenium/tbdriver.py
Fixed a bug in which the path of a specified custom profile was ignored.
=> Use specified custom profile when tbb_path and tbb_profile_path are provided
